name: rukunin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+47

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  web: ^1.1.1
  pdf: ^3.11.3
  excel: ^4.0.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  printing: ^5.14.2
  go_router: ^17.0.0
  share_plus: ^12.0.1
  flutter_native_splash: ^2.4.3
  image_picker: ^1.0.7
  image_picker_for_web: ^3.1.1
  firebase_storage: ^13.0.4
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.13.0
  webview_flutter_wkwebview: ^3.10.0
  url_launcher: ^6.2.0

  path: any
  git_hooks: any
  camera: ^0.11.3
  collection: any
  cached_network_image: ^3.4.1
  home_widget: ^0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/kk/
    - assets/ktp/
    - assets/icons/

flutter_launcher_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon_r.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FEAF0D"
  image: assets/icons/app_icon.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#FEAF0D"
    image: assets/icons/app_icon.png
